spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

app:
  rabbitmq:
    queues:
      speed: speed.queue
      safezone: safezone.queue
      heartbeat: heartbeat.queue
      oxygen: oxygen.queue
      battery: battery.queue
server:
  port: 8088
