spring:
  application:
    name: notification-service

  rabbitmq:
    host: ${RABBITMQ_PRIVATE_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

app:
  rabbitmq:
    queues:
      speed: speed.queue
      safezone: safezone.queue
      heartbeat: heartbeat.queue
      oxygen: oxygen.queue
      battery: battery.queue
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false