spring.application.name=identity-family


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/identity_family
spring.datasource.username=root
spring.datasource.password=12345678
debug=true
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# gRPC server configuration
grpc.server.port=9090
