spring.application.name=identity-family


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${railway}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
debug=true
server.port=8080
eureka.client.service-url.defaultZone=http://${EUREKA_URL}/eureka/

grpc.server.port=9090
