server:
  port: 8081

spring:
  application:
    name: gateway

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth
    username: postgres
    password: 12345678
    pool:
      enabled: true
      max-size: 10
      initial-size: 5

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-family
              uri: lb://IDENTITY-FAMILY
              predicates:
                - Path=/identity/**

            - id: device-gateway
              uri: lb://DEVICE-GATEWAY
              predicates:
                - Path=/device/**

            - id: geofencing-service
              uri: lb://GEOFENCING-SERVICE
              predicates:
                - Path=/geofencing/**

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**
            - id : daily-tracking-service
              uri: lb://DAILY-TRACKING-SERVICE
              predicates:
                - Path=/daily_tracking/**
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.postgresql: DEBUG

