server:
  port: 8081

spring:
  application:
    name: gateway

  r2dbc:
    url: r2dbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      max-size: 10
      initial-size: 5

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-family
              uri: ${FAMILY_SERVICE_URI}
              predicates:
                - Path=/identity/**

            - id: device-gateway
              uri: ${DEVICE_SERVICE_URI}
              predicates:
                - Path=/device/**

            - id: geofencing-service
              uri: ${GEOFENCING_SERVICE_URI}
              predicates:
                - Path=/geofencing/**

            - id: notification-service
              uri: ${NOTIFICATION_SERVICE_URI}
              predicates:
                - Path=/notifications/**

            - id : daily-tracking-service
              uri: ${DAILY_TRACKING_SERVICE_URI}
              predicates:
                - Path=/daily_tracking/**
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.postgresql: DEBUG
