spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false


app:
  mqtt:
    url: tcp://10.22.124.253:1883
    client-id: ingestion-service
server:
  port: 8087
