spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false


app:
  mqtt:
    url: ${EMQX_TCP_URL}
    client-id: ingestion-service
server:
  port: 8087
