spring:
  application:
    name: daily-tracking-service
  kafka:
    bootstrap-servers: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
  eureka:
    client:
      serviceUrl:
        defaultZone: http://${EUREKA_URL}/eureka/
    consumer:
      group-id: daily-tracking-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.dailytrackingservice.dto.Envelope
  r2dbc:
    url: r2dbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      max-size: 10
      initial-size: 5
  rabbitmq:
    host: ${RABBITMQ_PRIVATE_URL}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

app:
  kafka:
    topic:
     vitals: vitals
     battery: battery
     gps: gps

server:
  port: 8089


