spring:
  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerMetricAutoConfiguration
  application:
    name: device-gateway
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/devices
    username: postgres
    password: 12345678
    pool:
      enabled: true
      max-size: 10
      initial-size: 5
jwt:
  secret: k9Fv3xP8qZr7Lm2QwXc4B8N5tYh6JpR0uD1sE9aK7M3VxT2ZpLq8Wc5N4Yh1R6F
  expiration: 86400000
server:
  port: 8085

grpc:
  server:
    port: 9093

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true # Expose environment variables in /actuator/info