spring:
  application:
    name: geofencing-service
  rabbitmq:
    host: ${RABBITMQHOST}
    port: ${RABBITMQPORT}
    username: ${RABBITMQUSERNAME}
    password: ${RABBITMQPASSWORD}
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}

  r2dbc:
    url: r2dbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    pool:
      enabled: true
      max-size: 10
      initial-size: 5

  kafka:
    bootstrap-servers: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}

    consumer:
      group-id: geofencing-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.geofencingservice.dto.Envelope

app:
  kafka:
    topics:
      gps: gps
server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN}
    prefer-ip-address: false