spring:
  application:
    name: geofencing-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
  data:
    redis:
      host: redis
      port: 6379

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/geofencing

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: geofencing-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.geofencingservice.dto.Envelope

app:
  kafka:
    topics:
      gps: gps
server:
  port: 8086